#!name=奶茶模块-ww125.cn
#!desc=自用模块,模块来自网络或自己编写,学无止境！！
#!openUrl=https://t.me/Functional_Store_Hub
#!author=@Nameking77 https://t.me/Nameking77
#!homepage= https://raw.githubusercontent.com/ww125cn/Shadowrocket
#!manual=https://t.me/Functional_Store_Hub/10
#!icon= https://raw.githubusercontent.com/ww125cn/Shadowrocket/main/favicon.ico
#!other=Ww125Cn.Shadowrocket.model

[Script]
酷我音乐=type=http-response,pattern=^https?:\/\/.*\.(kuwo|lrts)\.(cn|me)\/(a\.p|music\.pay|(vip\/(v2|enc)\/(theme|user\/vip))|(EcomResource|(Mobile)?Ad)Serv(er|ice)).*,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/nameking77/Qx/main/rewrite/kw.js,script-update-interval=0

[MITM]
hostname = %APPEND% *.kuwo.cn, *.lrts.me
